
master:
  componentName: "jenkins-master"
  image: "jenkins/jenkins"
  tag: "lts"
  imagePullPolicy: "Always"
  imagePullSecretName:
  # Optionally configure lifetime for master-container
  lifecycle:
  #  postStart:
  #    exec:
  #      command:
  #      - "uname"
  #      - "-a"
  adminUser: "admin"
  # adminPassword: <defaults to random>

  # List of plugins to be install during Jenkins master start
  installPlugins:
    - kubernetes:1.25.7
    - workflow-job:2.39
    - workflow-aggregator:2.6
    - credentials-binding:1.22
    - git:4.2.2
    - configuration-as-code:1.41

  # List of plugins to install in addition to those listed in master.installPlugins
  additionalPlugins:
    - slack:2.40
    - greenballs:1.15
    - thinBackup:1.9

  # Jenkins XML job configs to provision
  jobs: {}
  #  test: |-
  #    <<xml here>>

  # Below is the implementation of Jenkins Configuration as Code.  Add a key under configScripts for each configuration area,
  # where each corresponds to a plugin or section of the UI.  Each key (prior to | character) is just a label, and can be any value.
  # Keys are only used to give the section a meaningful name.  The only restriction is they may only contain RFC 1123 \ DNS label
  # characters: lowercase letters, numbers, and hyphens.  The keys become the name of a configuration yaml file on the master in
  # /var/jenkins_home/casc_configs (by default) and will be processed by the Configuration as Code Plugin.  The lines after each |
  # become the content of the configuration yaml file.  The first line after this is a JCasC root element, eg jenkins, credentials,
  # etc.  Best reference is https://<jenkins_url>/configuration-as-code/reference.  The example below creates a welcome message:
  JCasC:
    enabled: true
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our CI\CD server. This Jenkins is configured and managed 'as code'.
      credentials: |
        credentials:
            system:
              domainCredentials:
              - credentials:
                # Credential to use with Rest API operations and Nexus Jenkins plugin
                - usernamePassword:
                    description: "Just test credential"
                    id: "test-credentials"
                    password: "admin123"
                    scope: GLOBAL
                    username: "admin"

  ingress:
    enabled: true
    paths: []
    apiVersion: "extensions/v1beta1"
    labels: {}
    annotations:
      kubernetes.io/tls-acme: "true" 
      kubernetes.io/ssl-redirect: "true" 
      kubernetes.io/ingress.class: "nginx" 
    hostName: jcasc.ddns.net
    tls:
      - secretName: acme-jenkins-app-tls
        hosts:
          - jcasc.ddns.net


persistence:
  enabled: true

